### PR TITLE
Integrate @Bastui design (Part. 1)

### PR DESCRIPTION
**Pull request by enzozccr**
Hello @bdebon !

I took up the challenge to integrate Bastui design. 
-> [Here is his original prototype](https://www.figma.com/proto/lceF92oVJ4QRAbnfddO5FL/BastiUi-%E2%80%A2-PrevYou?node-id=206%3A376&scaling=min-zoom&page-id=116%3A56)

Some preview of my integration :

https://user-images.githubusercontent.com/45360021/112723128-59ddff80-8f0d-11eb-9dfe-c9eca50d2a6f.mov

As you can see I still need to implement some interactions and stuff but the most things are done.

---

FYI I also did my own design try, you can get [Figma prototype here ](https://www.figma.com/proto/FkLpSesOMSJkQcVexj9EnQ/BenCode-(by-enzozccr)?node-id=8%3A260&scaling=min-zoom&page-id=0%3A1)

Related tweet : [https://twitter.com/ezccr/status/1375625957776719880](https://twitter.com/ezccr/status/1375625957776719880)

### CODE REVIEW

**Review by mlbonniec — APPROVED** [review]
Very smooth integration! Well done 👍🏻

**Comment by bdebon** [comment]
It does not work for me when I clone your fork, and try it on my machine, I can see the good integration (well done!) but the functionality are broken. Js errors, I can't see the preview of the thumbnail of the channel nor the thumbnail of the video. Is there something I do wrong?

**Comment by enzozccr** [comment]
> It does not work for me when I clone your fork, and try it on my machine, I can see the good integration (well done!) but the functionality are broken. Js errors, I can't see the preview of the thumbnail of the channel nor the thumbnail of the video. Is there something I do wrong?

Thank you :)
Yes I still need to add both uploaded channel + video thumbnails previews (I suck at JS tho)

**Comment by bdebon** [comment]
Because of this : 
image

I'm gonna need to make some changes on this pr before merging. But the job is well done so I'm fixing few stuff and merging it! Congrats :)

**Comment by enzozccr** [comment]
I'm glad you like it 👍 
There are a few things left that I haven't done like...

- animate the eyes (in the header and in the confirm button)
- hover states of uploaded thumbnails
- darkmode

Maybe I'll do it soon, else if someone wants to do it, feel free !

**Comment by bdebon** [comment]
Then just wait a little bit because I’m changing a loooooot of thing in the project and the problem with this small project is that there is only one main file so we have conflict every time… + we don’t have a linter and stuff like this so everyone introduce new formatting and stuff like this… Really annoying ahah. 
I will ask if someone is up to install a linter or something like this.

**Comment by BastiUi** [comment]
I made a version 2.2 of my Design 😄 
Informations detailed in this tweet : https://twitter.com/BastiUi/status/1376604022757527561

**Pull request merged**
