### PR TITLE
added the 'eyes following cursor'

### PR DESCRIPTION
**Pull request by BDeMot**
Hi,
During his livestream, BastiUi mentionned that the header eyes are meant to looks in the direction of cursor.
I was able to make this effect based on the cursor position in the popup.
Easy to modify to follow the cursor on a whole tab : 
=> only change : 
    - let mouseX = mouseevent.clientX;
    - let mouseY = mouseevent.clientY;

### CODE REVIEW

**Comment by bdebon** [comment]
I like the video game oriented way you developed this! 
It's cool. Only one question, I don't see where and how I can change the code to make it work for the whole tab. I think with the whole tab it could be more convincing but not sure about if it's possible.

**Comment by BDeMot** [comment]
I'm don't know anything about Chrome extensions. I tried to get the mouse position on the whole tab by injecting a Content script but was enable to make it works. 

Unfortunetaly I don't have enough time right now to dive into the Chrome Dev documentation.

**Comment by bdebon** [comment]
Okay, don't worry at all with the whole tab. I think to make it work we would have to do a lot of not beautiful things and I prefer to keep this simple. It's just that you wrote something about so I thought you had an easy solution and I was curious.
I merge this :)

**Comment by BDeMot** [comment]
I wrote this because I have the feeling that the solution is here but I'm too ignorant yet to make it works.

**Comment by bdebon** [comment]
You are listening an event on the popup, not on the current tab. If you want to be able to track this the way we want, we would have to do something really bad that listen event in the current tab, that store the result on the event in the local storage and make a listener on the local storage in the popup so that the popup knows everytime the mouse has move in the current tab. From the listener on the localstorage we could then apply modification to your eyes position in the popup. But I feel that it's not going to work easily and I don't think that writing so much things in the local storage is a good idea... Do you understand my explications?

**Comment by BDeMot** [comment]
Very clear !
In fact, I wanted to do something similar and store the mouse position on the session storage. But I wasn't even able to log it on the console :-D

**Comment by bdebon** [comment]
There is 2 console to check in this case. The console of your current tab, and the console of your popup. If you right click on it and inspect it, it will open the console of your popup. 
Did you know that or the problem is somewhere else?

**Comment by BDeMot** [comment]
I didn't knew about the popup console, thank you!

**Pull request merged**
