### PR TITLE
Fix input file bug with content script

### PR DESCRIPTION
**Pull request by Jorand**
@bdebon @benjaminrobinet 
After trying the proxy input proposed by @benjaminrobinet it put me on a way to try something else.
To get around the problem I have moved the popup in the content script and used an object element as iframe. and that made the input file window bug go away for me. 
Still need to try on latest macOS version.

Note: I had to fix the height of the popup because object height auto is not working.

### CODE REVIEW

**Comment by LudovicHe** [comment]
Works fine with MacOs BigSur 11.3 (dev bêta) ! 👍🏼

**Comment by bdebon** [comment]
I've merged your work on main mi Amigo! 
Congratulation it was perfect. 
I just added the border-radius on the popup and the fact that the popup closes itself when the upload of the thumbnail is successful!
Thank you very much!

**Comment by Jorand** [comment]
@bdebon Cool ! I'm happy to have contributed.
It was a fun exercise to do. 
@benjaminrobinet put me on the good path on the issue #6 , i think you can close it too.

**Comment by benjaminrobinet** [comment]
You are the boss 🏴‍☠️

**Pull request closed without merging**
