### PR TITLE
Improve UI and UX

### PR DESCRIPTION
**Pull request by mlbonniec**
This Pull Request is based on [this Tweet](https://twitter.com/HowardLawrenceB/status/1375394938788196355). I know this is a massive change, so I'll understand if my PR is rejected.  
But for the challenge of creating tabs in "pure" javascript, and in a Chrome extension, I made it 😄.

I tried to reproduce the Step System, as designed by Howard Bouchevereau.
Here's some examples of the 3 steps (for the moment I didn't implement the position option).

Step 1
Step 2
Step 3

And the result ⤵️

Visualize

### CODE REVIEW

**Comment by bdebon** [comment]
That's a massiv and very interesting work Mathis!
Thank you very much. I don't want to lose this work so I'm gonna merge it to the repo but on another branch. 
The new branch will be called design-tabs

**Comment by mlbonniec** [comment]
Thanks a lot!  
For the definitive UI, do you already have the mockup? Will you integrate it yourself (on Twitch)? Or are you going to leave the integration to the community.

**Comment by bdebon** [comment]
For the definitive UI i'm still waiting for all designers to propose stuff. I already know that I'm going to code the one proposed by BastiUI on his Twitter. He challenged me so I can't say no. The UI he made is quite good but not sure if it will be the definitive one. It depends if someone propose better in the coming days :)
He gave the public figma on his twitter so you can try it if you want!

**Comment by mlbonniec** [comment]
Yes I have seen it, it is great too!  
I would be excited to do it, but if you are going to do it too, or even someone else, I might leave it ahah, I don't know

**Comment by bdebon** [comment]
I finally merged it on tab-design-ux for the memory of your good work :)

**Pull request closed without merging**
